#!/usr/bin/env bash
# Writes ios/Flutter/DartDefines.xcconfig from an env/*.json file so Xcode Run
# gets the same --dart-define-from-file values as `flutter run`.
#
# Usage:
#   tool/sync_ios_dart_defines.sh                 # env/production.json
#   tool/sync_ios_dart_defines.sh env/staging.json
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
env_file="${1:-env/production.json}"
if [[ "$env_file" != /* ]]; then
  env_file="$root/$env_file"
fi

if [[ ! -f "$env_file" ]]; then
  echo "error: env file not found: $env_file" >&2
  exit 1
fi

out="$root/ios/Flutter/DartDefines.xcconfig"
python3 - "$env_file" "$out" <<'PY'
import base64, json, sys
from pathlib import Path

env_path, out_path = Path(sys.argv[1]), Path(sys.argv[2])
values = json.loads(env_path.read_text())
encoded = ",".join(
    base64.b64encode(f"{key}={value}".encode()).decode()
    for key, value in values.items()
)
# Append to Flutter's Generated.xcconfig DART_DEFINES (included first).
out_path.write_text(
    "// Generated by tool/sync_ios_dart_defines.sh from "
    f"{env_path.name}. Do not edit.\n"
    f"DART_DEFINES=$(DART_DEFINES),{encoded}\n"
)
print(f"Wrote {out_path} from {env_path.name}")
PY
