name: Update CSV Data Daily

on:
  schedule:
    # Run daily at 21 UTC
    - cron: '0 21 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-csvs:
    runs-on: ubuntu-latest
    steps:
    - name: Download updated CSV data
      run: npm run download-csvs:force
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/price-guide/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update CSV data $(date +'%Y-%m-%d')" && git push)

